project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "translations"
preserve_hierarchy: true
files:
  - source: "/**/*.pot"
    translation: "%original_path%/%file_name%.%locale_with_underscore%.po"
