project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: "."
preserve_hierarchy: true
files:
  - source: "/translations/**/*.pot"
    translation: "%original_path%/%file_name%.%locale_with_underscore%.po"

  - source: "/steam/storepage_550961_english.json"
    translation: "%original_path%/%file_name%_%language%.json"
    translation_replace:
      "_english": ""
